#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'


# Navegar a la carpeta de pruebas
cd src/JUS.Tests || exit 1

# Ejecutar los tests
dotnet test

# Guardar el estado de salida del comando dotnet test
RESULT=$?

# Regresar a la carpeta anterior
cd - || exit 1

# Salir con el estado de salida del comando dotnet test
exit $RESULT
